import { getLanguage } from '../../Components/Strings';
const ko = {
  manage: '내 상품 관리',
  market: '상품 둘러보기',
  orders: '내 주문',
  back: '뒤로',
  refresh: '새로고침',
  connect: '판매자 웹 연결',
  link: '담당자에게 받은 판매자 전용 웹 주소를 붙여 넣어 주세요.',
  connectButton: '연결하기',
  invalidLink: '판매자 전용 링크를 확인해 주세요.',
  add: '상품 등록',
  edit: '수정',
  web: '웹에서 관리',
  empty: '등록된 상품이 없습니다.',
  error: '불러오지 못했습니다. 연결 상태를 확인하고 다시 시도해 주세요.',
  saveError: '요청을 처리하지 못했습니다. 상품 정보와 재고를 새로고침한 뒤 다시 시도해 주세요.',
  published: '앱 공개 중',
  submitted: '검토 대기',
  rejected: '수정 요청',
  archived: '판매 중지',
  quantity: '수량 (1~20)',
  country: '배송 국가',
  buy: '결제하기',
  external: '판매처에서 구매',
  unavailable: '현재 앱 결제를 이용할 수 없습니다.',
  soldOut: '품절',
  loading: '불러오는 중…',
  orderEmpty: '주문 내역이 없습니다.',
  pending: '결제 확인 중',
  paid: '결제 완료 · 배송 준비',
  shipped: '배송 처리됨',
  expired: '결제 만료',
  failed: '결제 실패',
  refunded: '환불',
  webError: '페이지를 열지 못했습니다. 다시 시도해 주세요.',
  retry: '다시 시도',
  shipping: '배송비',
};
const en = {
  manage: 'My products',
  market: 'Browse products',
  orders: 'My orders',
  back: 'Back',
  refresh: 'Refresh',
  connect: 'Connect seller portal',
  link: 'Paste the private seller portal link provided by your account manager.',
  connectButton: 'Connect',
  invalidLink: 'Check your seller portal link.',
  add: 'Add product',
  edit: 'Edit',
  web: 'Manage on web',
  empty: 'No products yet.',
  error: 'Could not load. Check your connection and try again.',
  saveError: 'Could not complete the request. Refresh product availability and try again.',
  published: 'Published',
  submitted: 'Under review',
  rejected: 'Changes requested',
  archived: 'Not for sale',
  quantity: 'Quantity (1–20)',
  country: 'Shipping country',
  buy: 'Checkout',
  external: 'Buy from seller',
  unavailable: 'In-app checkout is currently unavailable.',
  soldOut: 'Sold out',
  loading: 'Loading…',
  orderEmpty: 'No orders yet.',
  pending: 'Awaiting payment',
  paid: 'Paid · preparing shipment',
  shipped: 'Shipped',
  expired: 'Checkout expired',
  failed: 'Payment failed',
  refunded: 'Refunded',
  webError: 'Could not open this page. Please try again.',
  retry: 'Retry',
  shipping: 'Shipping',
};
export const storeCopy = () => (getLanguage() === 'ko' ? ko : en);
export function productName(p) {
  return getLanguage() === 'en' ? p.nameEn || p.nameKo : p.nameKo;
}
export function productStatus(status) {
  const c = storeCopy();
  return (
    {
      PUBLISHED: c.published,
      SUBMITTED: c.submitted,
      APPROVED: c.submitted,
      REJECTED: c.rejected,
      ARCHIVED: c.archived,
    }[status] || status
  );
}
