import { Dimensions, StyleSheet } from 'react-native';
import T from '../../Components/Constants/DesignTokens';

const { COLORS, RADIUS, FONT } = T;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BG,
  },
  addVideoButtonContainer: {
    width: (Dimensions.get('window').width / 16) * 9,
    height: (Dimensions.get('window').width / 16) * 9,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.SURFACE,
    borderWidth: 1,
    borderColor: COLORS.LINE,
    borderRadius: RADIUS.CARD,
  },
  addVideoButtonImage: {
    width: 34,
    height: 34,
    margin: 20,
  },
  uploadVideoTitle: {
    color: COLORS.INK,
    fontSize: 15,
    fontFamily: FONT.Regular,
    alignSelf: 'center',
  },
  sectionContainer: {
    marginTop: 35,
    marginBottom: 5,
  },
  sectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 10,
  },
  sectionTitle: {
    color: COLORS.INK,
    fontSize: 16,
    fontFamily: FONT.SemiBold,
  },
  dataLength: {
    marginLeft: 6,
    fontSize: 12,
    fontFamily: FONT.Regular,
    color: COLORS.GREY,
  },
  // 영상 재생 영역만 어둡게 유지한다 — 밝은 배경 위에서 레터박스가 튀지 않게.
  mediaPlayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    backgroundColor: '#000000',
  },
  productRatingContainer: {
    marginHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  performanceRating: {
    flex: 3,
    textAlign: 'left',
    paddingHorizontal: 10,
    fontSize: 14,
  },
  ratingElement: {
    flex: 2,
    alignItems: 'center',
  },
  productRating: {
    flex: 1,
    color: COLORS.GREY,
    fontSize: 14,
    fontFamily: FONT.Regular,
    textAlign: 'right',
    marginRight: 10,
  },
  moveButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 20,
  },
  externalLinkProductContainer: {
    paddingHorizontal: 20,
  },
  textInput: {
    paddingHorizontal: 12,
    color: COLORS.INK,
    fontFamily: FONT.Regular,
    marginHorizontal: 20,
    flex: 1,
    fontSize: 14,
    borderWidth: 1,
    borderColor: COLORS.LINE,
    borderRadius: RADIUS.FIELD,
    backgroundColor: COLORS.SURFACE,
    paddingVertical: 10,
  },
  attachmentContainer: {
    marginLeft: 20,
    flexDirection: 'row',
  },
  addImageAttachmentButton: {
    width: 100,
    height: 100,
    borderRadius: RADIUS.CARD,
    borderColor: COLORS.LINE,
    borderWidth: 1,
    backgroundColor: COLORS.SURFACE,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  addImageAttachmentIcon: {
    width: 24,
    height: 24,
    marginBottom: 5,
  },
  attachmentItemListContainer: {
    marginRight: 10,
  },
  attachmentImage: {
    width: 100,
    height: 100,
    borderRadius: RADIUS.CARD,
    borderColor: COLORS.LINE,
    borderWidth: 1,
  },
  removeAttachmentButton: {
    position: 'absolute',
    right: 5,
    top: 5,
    width: 18,
    height: 18,
  },
  removeVideoButton: {
    position: 'absolute',
    right: 10,
    top: 10,
    width: 18,
    height: 18,
  },
  removeLinkedProductButton: {
    position: 'absolute',
    right: 36,
    top: 24,
    width: 24,
    height: 24,
  },
  requiredIcon: {
    width: 8,
    height: 10,
    marginLeft: 4,
  },
  moveIcon: {
    width: 10,
    height: 18,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.LINE,
    marginHorizontal: 20,
  },
  fieldTitleError: {
    color: COLORS.RED,
    fontSize: 14,
    fontFamily: FONT.Regular,
    lineHeight: 18,
    paddingHorizontal: 20,
    alignSelf: 'center',
  },
  verticleLine: {
    height: '100%',
    width: 1,
    marginLeft: -4,
    marginRight: 6,
    backgroundColor: COLORS.LINE,
  },
  headerTextRightButton: {
    marginRight: 20,
    color: COLORS.AMBER_DEEP,
    fontSize: 14,
    fontFamily: FONT.SemiBold,
  },
  hashTagTextInput: {
    flex: 1,
    fontSize: 14,
    color: COLORS.INK,
    fontFamily: FONT.Regular,
    borderWidth: 1,
    borderColor: COLORS.LINE,
    borderRadius: RADIUS.FIELD,
    backgroundColor: COLORS.SURFACE,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  hashTagListContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: 20,
    marginTop: 10,
  },
  hashTagList: {
    borderWidth: 1,
    borderRadius: 20,
    borderColor: COLORS.LINE,
    backgroundColor: COLORS.SURFACE,
    marginRight: 10,
    paddingVertical: 5,
    paddingHorizontal: 11,
    flexDirection: 'row',
    marginBottom: 5,
  },
  hashTagItem: { fontFamily: FONT.Medium, fontSize: 12.5, color: COLORS.INK },
});

export default styles;
