import { Dimensions, StyleSheet } from 'react-native';
import Constants from '../../Components/Constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Constants.COLOR_BACKGROUND_DARK,
  },
  addVideoButtonContainer: {
    width: (Dimensions.get('window').width / 16) * 9,
    height: (Dimensions.get('window').width / 16) * 9,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgb(31, 31, 31)',
    borderRadius: 14,
  },
  addVideoButtonImage: {
    width: 34,
    height: 34,
    margin: 20,
  },
  uploadVideoTitle: {
    color: Constants.COLOR_BACKGROUND_DARK,
    fontSize: 15,
    fontFamily: Constants.CUSTOM_FONTS.SUIT.REGULAR,
    alignSelf: 'center',
  },
  sectionContainer: {
    marginTop: 35,
    marginBottom: 5,
  },
  sectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 10,
  },
  sectionTitle: {
    color: Constants.TIER_COLORS.ARTISAN,
    fontSize: 16,
    fontFamily: Constants.CUSTOM_FONTS.SUIT.REGULAR,
  },
  dataLength: {
    marginLeft: 6,
    fontSize: 12,
    fontFamily: Constants.CUSTOM_FONTS.SUIT.REGULAR,
    color: Constants.TIER_COLORS.ARTISAN,
  },
  mediaPlayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    backgroundColor: Constants.COLOR_BACKGROUND_DARK,
  },
  productRatingContainer: {
    marginHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  performanceRating: {
    flex: 3,
    textAlign: 'left',
   paddingHorizontal: 10,
   fontSize: 14,
  },
  ratingElement: {
    flex: 2,
    alignItems: 'center',
  },
  productRating: {
    flex: 1,
    color: Constants.TIER_COLORS.STRIVER,
    fontSize: 14,
    fontFamily: Constants.CUSTOM_FONTS.SUIT.REGULAR,
    textAlign: 'right',
    marginRight: 10,
    
  },
  moveButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 20,
  },
  externalLinkProductContainer: {
    paddingHorizontal: 20,
  },
  textInput: {
    paddingHorizontal: 10,
    color: Constants.TIER_COLORS.ARTISAN,
    fontFamily: Constants.CUSTOM_FONTS.SUIT.REGULAR,
    marginHorizontal: 20,
    flex: 1,
    fontSize: 14,
    borderWidth: 1,
    borderColor: Constants.TIER_COLORS.STRIVER,
    paddingVertical: 6,
  },
  attachmentContainer: {
    marginLeft: 20,
    flexDirection: 'row',
  },
  addImageAttachmentButton: {
    width: 100,
    height: 100,
    borderRadius: 14,
    borderColor: Constants.TIER_COLORS.STRIVER,
    borderWidth: 1,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  addImageAttachmentIcon: {
    width: 24,
    height: 24,
    marginBottom: 5,
  },
  attachmentItemListContainer: {
    marginRight: 10,
  },
  attachmentImage: {
    width: 100,
    height: 100,
    borderRadius: 14,
    borderColor: Constants.TIER_COLORS.OPERATOR,
    borderWidth: 1,
  },
  removeAttachmentButton: {
    position: 'absolute',
    right: 5,
    top: 5,
    width: 18,
    height: 18,
  },
  removeVideoButton: {
    position: 'absolute',
    right: 10,
    top: 10,
    width: 18,
    height: 18,
  },
  removeLinkedProductButton: {
    position: 'absolute',
    right: 36,
    top: 24,
    width: 24,
    height: 24,
  },
  requiredIcon: {
    width: 8,
    height: 10,
    marginLeft: 4,
  },
  moveIcon: {
    width: 10,
    height: 18,
  },
  divider: {
    height: 1,
    backgroundColor: Constants.TIER_COLORS.STRIVER,
    marginHorizontal: 20,
  },
  fieldTitleError: {
    color: 'rgba(255, 0, 0, 0.8)',
    fontSize: 14,
    fontFamily: Constants.CUSTOM_FONTS.SUIT.REGULAR,
    lineHeight: 18,
    paddingHorizontal: 20,
    alignSelf: 'center',
  },
  verticleLine: {
    height: '100%',
    width: 1,
    marginLeft: -4,
    marginRight: 6,
    backgroundColor: Constants.TIER_COLORS.STRIVER,
  },
  headerTextRightButton: {
    marginRight: 20,
    textDecorationLine: 'underline',
    // color: '#888888',
    color: Constants.COLOR_POINT_BLUE,
    fontSize: 14,
    fontFamily: Constants.CUSTOM_FONTS.SCDREAM.REGULAR_4,
  },
  hashTagTextInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: Constants.CUSTOM_FONTS.SUIT.REGULAR,
    borderWidth: 1,
    borderColor: Constants.TIER_COLORS.STRIVER,
    paddingVertical: 6,
  },
  hashTagListContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: 20,
    marginTop: 10,
  },
  hashTagList: {
    borderWidth: 1,
    borderRadius: 20,
    borderColor: Constants.TIER_COLORS.ARTISAN,
    marginRight: 10,
    paddingVertical: 4,
    paddingHorizontal: 10,
    flexDirection: 'row',
    marginBottom: 5,
  },
  hashTagItem: { fontFamily: Constants.CUSTOM_FONTS.SUIT.REGULAR, color: Constants.TIER_COLORS.ARTISAN },
});

export default styles;
