// 공동구매 화면 문구 (2026-09-30) — StoreScreen/strings.js와 같은 방식(앱 언어 ko/en)
import { getLanguage } from '../../Components/Strings';

const ko = {
  eyebrow: '공동구매',
  back: '뒤로',
  retry: '다시 시도',
  loadError: '불러오지 못했어요. 연결 상태를 확인하고 다시 시도해 주세요.',
  notFound: '공동구매를 찾을 수 없어요. 링크가 만료됐거나 비공개 상태예요.',
  mockNotice: '개발용 테스트 데이터예요. 실제 결제는 일어나지 않아요.',

  // 상태
  state: {
    PENDING_HOST: '호스트 수락 대기',
    SCHEDULED: '오픈 예정',
    OPEN: '모집 중',
    CLOSED: '마감 · 결제 진행 중',
    CONFIRMED: '공동구매 성사',
    SHIPPING: '배송 중',
    DONE: '배송 완료',
    FAILED: '최소 수량 미달',
    CANCELLED: '취소됨',
  },
  orderState: {
    BILLING_PENDING: '카드 등록 전',
    RESERVED: '결제 예약됨',
    PAID: '결제 완료 · 배송 준비',
    PAYMENT_FAILED: '결제 실패',
    SHIPPED: '발송됨',
    VOIDED: '미달로 결제 안 됨',
    CANCELLED: '취소됨',
  },

  // 상세
  hostSays: '호스트 한마디',
  hostVideos: '호스트 영상',
  detail: '상세 정보',
  noDetail: '브랜드 상세페이지가 아직 등록되지 않았어요.',
  price: '공동구매가',
  listPrice: '정가',
  off: (n) => `${n}% 할인`,
  shippingFee: '배송비',
  freeShipping: '무료배송',
  country: (c) => `판매 국가 · ${c === 'JP' ? '일본' : '대한민국'}`,
  perUser: (n) => `1인 최대 ${n}개`,
  shipBy: (d) => `발송 예정 · ${d}`,
  progress: (q, min) => `${q} / ${min}개 모였어요`,
  noMin: (q) => `${q}개 예약됨`,
  left: ({ days, hours, minutes }) =>
    days > 0 ? `마감까지 ${days}일 ${hours}시간` : `마감까지 ${hours}시간 ${minutes}분`,
  startsIn: ({ days, hours }) => `오픈까지 ${days}일 ${hours}시간`,
  howItWorks: (min) =>
    min > 0
      ? `지금은 카드만 등록해 두고, 마감 때 ${min}개 이상 모이면 한 번에 결제돼요. 모자라면 결제되지 않아요.`
      : '지금은 카드만 등록해 두고, 마감 때 한 번에 결제돼요.',
  ctaJoin: '공동구매 참여하기',
  ctaSoon: '오픈 전이에요',
  ctaClosed: '마감됐어요',
  ctaSoldOut: '준비된 수량이 모두 찼어요',
  ctaMore: '추가로 참여하기',
  myOrders: '내 참여',
  failedNote: '최소 수량이 모이지 않아 공동구매가 취소됐어요. 결제는 일어나지 않았어요.',
  cancelledNote: '공동구매가 취소됐어요. 결제는 일어나지 않았어요.',
  disclosure: '호스트는 이 공동구매의 판매 실적에 따라 브랜드로부터 수수료를 받아요.',
  seller: (brand) => `판매 · ${brand} / 운영 · 아르바임(GREYD)`,
  share: '공유하기',
  shareMessage: (title, url) => `${title}\n${url}`,

  // 주문서
  orderTitle: '주문서',
  option: '옵션',
  quantity: '수량',
  recipient: '받는 분',
  name: '이름',
  phone: '휴대폰 번호',
  postalCode: '우편번호',
  address1: '주소',
  address2: '상세 주소',
  memo: '배송 메모 (선택)',
  useSaved: '저장된 배송지 불러오기',
  total: '결제 예정 금액',
  chargeAt: (d) => `${d} 마감 후 결제`,
  agreeCharge: (d, min) =>
    min > 0
      ? `마감(${d}) 때 ${min}개 이상 모이면 등록한 카드로 결제되는 것에 동의해요. 미달이면 결제되지 않아요.`
      : `마감(${d}) 때 등록한 카드로 결제되는 것에 동의해요.`,
  agreeThirdParty: (brand) =>
    `배송을 위해 이름·연락처·주소·주문 내역을 판매 브랜드(${brand})에 제공하는 것에 동의해요. (보유: 배송 완료 후 3개월)`,
  submit: '카드 등록하고 참여하기',
  mockSubmit: '(테스트) 카드 등록 건너뛰고 참여하기',
  cancelNote: '마감 전에는 언제든 참여를 취소할 수 있어요.',
  error: {
    closed: '지금은 참여할 수 없어요.',
    quantity: '수량을 확인해 주세요.',
    perUserMax: '1인 최대 수량을 넘었어요.',
    soldOut: '남은 수량보다 많아요.',
    option: '옵션을 골라 주세요.',
    name: '받는 분 이름을 입력해 주세요.',
    phone: '휴대폰 번호를 확인해 주세요.',
    postalCode: '우편번호를 확인해 주세요.',
    address: '주소를 입력해 주세요.',
    agree: '필수 동의 항목에 체크해 주세요.',
    generic: '요청을 처리하지 못했어요. 잠시 후 다시 시도해 주세요.',
  },
  joinedTitle: '참여 완료',
  joinedBody: (d) => `결제가 예약됐어요. ${d} 마감 후 결과를 알려드릴게요.`,
  billingFailed: '카드 등록이 완료되지 않았어요. 다시 시도해 주세요.',
  billingTitle: '카드 등록',
  billingClose: '닫기',

  // 내 공동구매
  myTitle: '내 공동구매',
  tabJoined: '참여한 공동구매',
  tabHosting: '내가 여는 공동구매',
  emptyJoined: '참여한 공동구매가 없어요.',
  emptyHosting: '아직 받은 공동구매 제안이 없어요.',
  track: '배송 조회',
  trackNo: (courier, no) => `${courier} ${no}`,
  cancelJoin: '참여 취소',
  cancelConfirm: '참여를 취소할까요? 카드 등록도 해제돼요.',
  cancelDone: '취소했어요.',
  yes: '확인',
  no: '닫기',
  failure: {
    EXCEED_MAX_AMOUNT: '카드 한도 초과',
    INVALID_CARD: '사용할 수 없는 카드',
  },
  paymentFailedNote: '등록한 카드로 결제하지 못했어요. 고객센터로 문의해 주세요.',

  // 호스트
  hostTitle: '공동구매 호스트',
  invite: (brand) => `${brand}에서 공동구매 호스트를 제안했어요`,
  inviteBody:
    '수락하면 내 이름과 영상으로 공동구매 페이지가 열려요. 가격·물량·배송·CS는 브랜드와 아르바임이 맡고, 나는 영상 공유만 하면 돼요.',
  accept: '수락하기',
  decline: '거절하기',
  declineConfirm: '제안을 거절할까요? 거절하면 되돌릴 수 없어요.',
  note: '호스트 한마디',
  notePlaceholder: '왜 이 제품을 추천하는지 한두 줄로 적어 주세요.',
  saveNote: '저장',
  saved: '저장했어요.',
  videos: '공동구매에 붙일 영상',
  videosHint: '내가 올린 리뷰 영상 중 공동구매 페이지에 보여줄 것을 골라 주세요.',
  attach: '붙이기',
  detach: '빼기',
  upload: '새 영상 올리기',
  noVideos: '올린 영상이 없어요. 새 영상을 먼저 올려 주세요.',
  shareKit: '공유 링크',
  shareHint: '게시물에 "광고" 또는 "유료 광고 포함"을 꼭 표기해 주세요.',
  copyLink: '링크 공유',
  stats: (q, n) => `예약 ${q}개 · 참여 ${n}명`,
  preview: '공동구매 페이지 보기',

  // 브랜드
  brandTitle: '공동구매 관리',
  brandEmpty: '진행 중인 공동구매가 없어요.',
  create: '공동구매 열기',
  createTitle: '공동구매 열기',
  form: {
    title: '공동구매 이름',
    product: '상품',
    productHint: '판매자 스토어에 등록·승인된 상품만 고를 수 있어요.',
    noProducts: '승인된 상품이 없어요. 먼저 상품을 등록해 주세요.',
    host: '호스트 인플루언서 (@아이디)',
    hostHint: '지정한 인플루언서가 수락해야 공개돼요.',
    country: '판매 국가',
    kr: '대한민국 (KRW)',
    jp: '일본 (JPY)',
    price: '공동구매가',
    shippingFee: '배송비 (0 = 무료)',
    minQuantity: '최소 수량 (0 = 제한 없음)',
    maxQuantity: '최대 수량 (0 = 제한 없음)',
    perUserMax: '1인 최대 수량',
    options: '옵션 (쉼표로 구분, 선택)',
    detailImages: '상세페이지 이미지 URL (줄마다 하나, https)',
    startsAt: '시작 (YYYY-MM-DD HH:mm)',
    endsAt: '마감 (YYYY-MM-DD HH:mm)',
    shipBy: '발송 예정일 (YYYY-MM-DD, 선택)',
    submit: '호스트에게 제안 보내기',
  },
  formError: {
    title: '공동구매 이름을 입력해 주세요.',
    product: '상품을 골라 주세요.',
    host: '호스트 아이디를 입력해 주세요.',
    country: '판매 국가를 골라 주세요.',
    price: '공동구매가를 확인해 주세요.',
    priceAboveList: '공동구매가가 정가보다 높아요.',
    quantity: '수량은 0 이상의 정수로 입력해 주세요.',
    minAboveMax: '최소 수량이 최대 수량보다 커요.',
    perUser: '1인 최대 수량은 1 이상이어야 해요.',
    period: '기간을 확인해 주세요. 마감은 시작보다 뒤이고 미래여야 해요.',
    periodTooLong: '모집 기간은 최대 30일이에요.',
    detailImages: '이미지 주소는 https로 시작해야 해요.',
    host_not_found: '해당 아이디의 인플루언서를 찾을 수 없어요.',
    generic: '공동구매를 열지 못했어요. 잠시 후 다시 시도해 주세요.',
  },
  created: '호스트에게 제안을 보냈어요. 수락하면 공개돼요.',
  cancelGb: '공동구매 취소',
  cancelGbConfirm: '공동구매를 취소할까요? 결제 예약은 모두 해제되고 결제되지 않아요.',
  orders: '주문 명단',
  ordersLocked: '결제가 끝나면(마감 후 판정) 받는 분 명단이 공개돼요.',
  summary: ({ reserved, paid, failed, shipped }) =>
    `예약 ${reserved} · 결제 ${paid} · 실패 ${failed} · 발송 ${shipped}`,
  exportCsv: '명단 내보내기 (CSV)',
  courier: '택배사',
  trackingNumber: '송장번호',
  saveShipment: '발송 처리',
  editShipment: '송장 수정',
  shipmentError: '택배사와 송장번호를 확인해 주세요.',
  shipped: '발송 처리했어요.',
  simulateClose: '(테스트) 지금 마감 처리',
  pickCourier: '택배사 선택',
  // 상세 v2 (2026-09-30)
  tabs: { detail: '상세정보', host: '호스트', guide: '구매 안내' },
  groupPrice: '공동구매가',
  save: (amount) => `정가보다 ${amount} 저렴해요`,
  goalLeft: (n) => `목표까지 ${n}개 남았어요`,
  goalReached: '목표 달성! 마감 때 한 번에 결제돼요',
  buyers: (n) => `${n}명 참여 중`,
  recent: (name, q, min) =>
    `${name}님이 ${q}개 참여 · ${min < 1 ? '방금' : min < 60 ? `${min}분 전` : `${Math.floor(min / 60)}시간 전`}`,
  endsIn: '마감까지',
  startsInLabel: '오픈까지',
  clock: ({ days, hours, minutes, seconds }) =>
    `${days > 0 ? `${days}일 ` : ''}${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`,
  moreDetail: '상세정보 더보기',
  lessDetail: '상세정보 접기',
  steps: [
    ['카드 등록', '지금은 카드만 등록해요. 돈은 나가지 않아요.'],
    ['마감 판정', '마감 시각에 모인 수량을 확인해요.'],
    ['일괄 결제', '목표를 넘으면 등록한 카드로 한 번에 결제돼요. 미달이면 결제되지 않아요.'],
    ['발송', '브랜드가 직접 보내고, 송장번호로 배송을 조회할 수 있어요.'],
  ],
  shippingTitle: '배송 안내',
  returnsTitle: '교환·반품·환불',
  sellerTitle: '판매자 정보',
  faqTitle: '자주 묻는 질문',
  faq: [
    [
      '언제 결제되나요?',
      '마감 시각에 목표 수량을 넘으면 등록한 카드로 자동 결제돼요. 그 전에는 결제되지 않아요.',
    ],
    [
      '참여를 취소할 수 있나요?',
      '마감 전에는 내 공동구매에서 언제든 취소할 수 있어요. 카드 등록도 함께 해제돼요.',
    ],
    [
      '목표를 못 채우면요?',
      '공동구매가 취소되고 아무도 결제되지 않아요. 결과는 알림으로 알려드려요.',
    ],
    [
      '결제가 실패하면요?',
      '한도 초과 등으로 결제되지 않으면 그 주문만 취소되고 알림으로 안내해요.',
    ],
  ],
  notify: '오픈 알림 받기',
  notifyOn: '알림 신청됨 · 끄기',
  notifyDone: '오픈하면 알려드릴게요.',
  sheetTitle: '옵션 선택',
  toOrder: '주문서 작성',
  totalLabel: '합계',
  shipIncluded: (fee) => `배송비 ${fee} 포함`,
  soldLeft: (n) => `남은 수량 ${n}개`,
};

const en = {
  eyebrow: 'Group buy',
  back: 'Back',
  retry: 'Retry',
  loadError: 'Could not load. Check your connection and try again.',
  notFound: 'This group buy is unavailable. The link may have expired.',
  mockNotice: 'Development test data. No real payment happens.',
  state: {
    PENDING_HOST: 'Awaiting host',
    SCHEDULED: 'Opening soon',
    OPEN: 'Open',
    CLOSED: 'Closed · charging',
    CONFIRMED: 'Confirmed',
    SHIPPING: 'Shipping',
    DONE: 'Delivered',
    FAILED: 'Minimum not reached',
    CANCELLED: 'Cancelled',
  },
  orderState: {
    BILLING_PENDING: 'Card not registered',
    RESERVED: 'Payment reserved',
    PAID: 'Paid · preparing',
    PAYMENT_FAILED: 'Payment failed',
    SHIPPED: 'Shipped',
    VOIDED: 'Not charged (minimum not met)',
    CANCELLED: 'Cancelled',
  },
  hostSays: 'From the host',
  hostVideos: 'Host videos',
  detail: 'Details',
  noDetail: 'The brand has not added a detail page yet.',
  price: 'Group price',
  listPrice: 'Regular',
  off: (n) => `${n}% off`,
  shippingFee: 'Shipping',
  freeShipping: 'Free shipping',
  country: (c) => `Ships to · ${c === 'JP' ? 'Japan' : 'Korea'}`,
  perUser: (n) => `Up to ${n} per person`,
  shipBy: (d) => `Ships by · ${d}`,
  progress: (q, min) => `${q} / ${min} reserved`,
  noMin: (q) => `${q} reserved`,
  left: ({ days, hours, minutes }) =>
    days > 0 ? `${days}d ${hours}h left` : `${hours}h ${minutes}m left`,
  startsIn: ({ days, hours }) => `Opens in ${days}d ${hours}h`,
  howItWorks: (min) =>
    min > 0
      ? `Register a card now. If ${min}+ are reserved by the deadline, everyone is charged at once. Otherwise nobody is charged.`
      : 'Register a card now. Everyone is charged at once when it closes.',
  ctaJoin: 'Join group buy',
  ctaSoon: 'Not open yet',
  ctaClosed: 'Closed',
  ctaSoldOut: 'Fully reserved',
  ctaMore: 'Join again',
  myOrders: 'My reservations',
  failedNote: 'The minimum was not reached, so this group buy was cancelled. You were not charged.',
  cancelledNote: 'This group buy was cancelled. You were not charged.',
  disclosure: 'The host earns a commission from the brand on sales from this group buy.',
  seller: (brand) => `Sold by ${brand} · Operated by Arbaim (GREYD)`,
  share: 'Share',
  shareMessage: (title, url) => `${title}\n${url}`,
  orderTitle: 'Order',
  option: 'Option',
  quantity: 'Quantity',
  recipient: 'Recipient',
  name: 'Name',
  phone: 'Mobile number',
  postalCode: 'Postal code',
  address1: 'Address',
  address2: 'Address line 2',
  memo: 'Delivery note (optional)',
  useSaved: 'Use saved address',
  total: 'Amount to be charged',
  chargeAt: (d) => `Charged after ${d}`,
  agreeCharge: (d, min) =>
    min > 0
      ? `I agree my card will be charged at close (${d}) if ${min}+ are reserved. No charge otherwise.`
      : `I agree my card will be charged at close (${d}).`,
  agreeThirdParty: (brand) =>
    `I agree to share my name, phone, address and order with the brand (${brand}) for delivery. (Kept 3 months after delivery)`,
  submit: 'Register card & join',
  mockSubmit: '(Test) Skip card registration & join',
  cancelNote: 'You can cancel any time before it closes.',
  error: {
    closed: 'This group buy is not accepting orders.',
    quantity: 'Check the quantity.',
    perUserMax: 'Over the per-person limit.',
    soldOut: 'Not enough quantity left.',
    option: 'Choose an option.',
    name: 'Enter the recipient name.',
    phone: 'Check the mobile number.',
    postalCode: 'Check the postal code.',
    address: 'Enter the address.',
    agree: 'Please accept the required terms.',
    generic: 'Could not complete the request. Please try again.',
  },
  joinedTitle: 'You are in',
  joinedBody: (d) => `Your payment is reserved. We will let you know after it closes on ${d}.`,
  billingFailed: 'Card registration was not completed. Please try again.',
  billingTitle: 'Register card',
  billingClose: 'Close',
  myTitle: 'My group buys',
  tabJoined: 'Joined',
  tabHosting: 'Hosting',
  emptyJoined: 'You have not joined any group buys.',
  emptyHosting: 'No hosting offers yet.',
  track: 'Track',
  trackNo: (courier, no) => `${courier} ${no}`,
  cancelJoin: 'Cancel',
  cancelConfirm: 'Cancel this reservation? Your card registration will be released.',
  cancelDone: 'Cancelled.',
  yes: 'OK',
  no: 'Close',
  failure: {
    EXCEED_MAX_AMOUNT: 'Card limit exceeded',
    INVALID_CARD: 'Card not usable',
  },
  paymentFailedNote: 'We could not charge your card. Please contact support.',
  hostTitle: 'Group buy host',
  invite: (brand) => `${brand} invited you to host a group buy`,
  inviteBody:
    'If you accept, a group buy page opens with your name and videos. The brand and Arbaim handle price, stock, shipping and support — you just share.',
  accept: 'Accept',
  decline: 'Decline',
  declineConfirm: 'Decline this offer? This cannot be undone.',
  note: 'Your note',
  notePlaceholder: 'A line or two on why you recommend it.',
  saveNote: 'Save',
  saved: 'Saved.',
  videos: 'Videos on the page',
  videosHint: 'Pick which of your review videos to show on the group buy page.',
  attach: 'Add',
  detach: 'Remove',
  upload: 'Upload a new video',
  noVideos: 'No uploaded videos yet. Upload one first.',
  shareKit: 'Share link',
  shareHint: 'Always label your post as an ad / paid partnership.',
  copyLink: 'Share link',
  stats: (q, n) => `${q} reserved · ${n} buyers`,
  preview: 'View group buy page',
  brandTitle: 'Group buys',
  brandEmpty: 'No group buys yet.',
  create: 'Open a group buy',
  createTitle: 'Open a group buy',
  form: {
    title: 'Group buy name',
    product: 'Product',
    productHint: 'Only approved products in your seller store can be used.',
    noProducts: 'No approved products. Register a product first.',
    host: 'Host influencer (@handle)',
    hostHint: 'It goes live after the host accepts.',
    country: 'Country',
    kr: 'Korea (KRW)',
    jp: 'Japan (JPY)',
    price: 'Group price',
    shippingFee: 'Shipping fee (0 = free)',
    minQuantity: 'Minimum quantity (0 = none)',
    maxQuantity: 'Maximum quantity (0 = unlimited)',
    perUserMax: 'Max per person',
    options: 'Options (comma separated, optional)',
    detailImages: 'Detail image URLs (one per line, https)',
    startsAt: 'Starts (YYYY-MM-DD HH:mm)',
    endsAt: 'Ends (YYYY-MM-DD HH:mm)',
    shipBy: 'Ships by (YYYY-MM-DD, optional)',
    submit: 'Send offer to host',
  },
  formError: {
    title: 'Enter a name.',
    product: 'Choose a product.',
    host: 'Enter the host handle.',
    country: 'Choose a country.',
    price: 'Check the price.',
    priceAboveList: 'Group price is above the regular price.',
    quantity: 'Quantities must be whole numbers ≥ 0.',
    minAboveMax: 'Minimum is above maximum.',
    perUser: 'Max per person must be at least 1.',
    period: 'Check the period. The end must be after the start and in the future.',
    periodTooLong: 'The period can be at most 30 days.',
    detailImages: 'Image URLs must start with https.',
    host_not_found: 'No influencer with that handle.',
    generic: 'Could not open the group buy. Please try again.',
  },
  created: 'Offer sent. It goes live when the host accepts.',
  cancelGb: 'Cancel group buy',
  cancelGbConfirm: 'Cancel this group buy? All reservations are released and nobody is charged.',
  orders: 'Order list',
  ordersLocked: 'Recipient details appear once payment is completed after close.',
  summary: ({ reserved, paid, failed, shipped }) =>
    `Reserved ${reserved} · Paid ${paid} · Failed ${failed} · Shipped ${shipped}`,
  exportCsv: 'Export list (CSV)',
  courier: 'Courier',
  trackingNumber: 'Tracking number',
  saveShipment: 'Mark shipped',
  editShipment: 'Edit tracking',
  shipmentError: 'Check the courier and tracking number.',
  shipped: 'Marked as shipped.',
  simulateClose: '(Test) Close now',
  pickCourier: 'Choose courier',
  tabs: { detail: 'Details', host: 'Host', guide: 'How it works' },
  groupPrice: 'Group price',
  save: (amount) => `${amount} off the regular price`,
  goalLeft: (n) => `${n} more to reach the goal`,
  goalReached: 'Goal reached! Everyone is charged at close',
  buyers: (n) => `${n} joined`,
  recent: (name, q, min) =>
    `${name} joined with ${q} · ${min < 1 ? 'just now' : min < 60 ? `${min}m ago` : `${Math.floor(min / 60)}h ago`}`,
  endsIn: 'Ends in',
  startsInLabel: 'Opens in',
  clock: ({ days, hours, minutes, seconds }) =>
    `${days > 0 ? `${days}d ` : ''}${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`,
  moreDetail: 'Show full details',
  lessDetail: 'Show less',
  steps: [
    ['Register a card', 'Nothing is charged now.'],
    ['Close', 'We check the total at the deadline.'],
    ['Charge', 'If the goal is met, everyone is charged at once. Otherwise nobody is.'],
    ['Ship', 'The brand ships directly. Track it with the tracking number.'],
  ],
  shippingTitle: 'Shipping',
  returnsTitle: 'Returns & refunds',
  sellerTitle: 'Seller',
  faqTitle: 'FAQ',
  faq: [
    ['When am I charged?', 'Only at the deadline, and only if the goal is reached.'],
    [
      'Can I cancel?',
      'Any time before it closes, from My group buys. Your card registration is released.',
    ],
    [
      'What if the goal is not reached?',
      'The group buy is cancelled and nobody is charged. We will notify you.',
    ],
    ['What if my payment fails?', 'Only that order is cancelled and we will let you know.'],
  ],
  notify: 'Notify me when it opens',
  notifyOn: 'Notification on · Turn off',
  notifyDone: 'We will let you know when it opens.',
  sheetTitle: 'Choose options',
  toOrder: 'Continue to order',
  totalLabel: 'Total',
  shipIncluded: (fee) => `incl. ${fee} shipping`,
  soldLeft: (n) => `${n} left`,
};

export const gbCopy = () => (getLanguage() === 'ko' ? ko : en);
export const lang = () => (getLanguage() === 'ko' ? 'ko' : 'en');
