
auth.token=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

defaults.org=arbaim
defaults.project=react-native

defaults.url=https://sentry.io/
