export const UPLOADING_VIDEO = {
  ADD: 'UPLOADING_VIDEO_ADD',
  DELETE: 'UPLOADING_VIDEO_DELETE',
  UPDATE: 'UPLOADING_VIDEO_UPDATE',
  UPLOAD: 'UPLOADING_VIDEO_UPLOAD',
  UPLOAD_COMPLETE: 'UPLOADING_VIDEO_UPLOAD_COMPLETE',
  UPLOAD_ERROR: 'UPLOADING_VIDEO_UPLOAD_ERROR',
  STOP: 'UPLOADING_VIDEO_STOP',
  UPLOAD_PROGRESS: 'UPLOADING_VIDEO_UPLOAD_PROGRESS',
};

export const REGION = {
  SET: 'REGION_SET',
};

export const USER = {
  SET: 'USER_SET',
  UPDATE: 'USER_UPDATE',
  DELETE: 'USER_DELETE',
};
