import Strings from '../Strings';

// CODES
const POST_STATUS_CODE = {
  NORMAL: 0,
  DELETED: 1,
  REPORTED: 2,
  DELETED_BY_ADMIN: 3,
};

const USER_STATUS_CODE = {
  NORMAL: 0,
  NOT_MEMBER_YET: 1,
  PAUSED: 2,
};

const ORDER_STATUS_CODE = {
  OUTSTANDING: 0,
  NOT_ACCEPTED: 1,
  PREPARING: 2,
  SHIPPING: 3,
  SHIPMENT_COMPLETED: 4,
  PURCHASE_COMPLETED: 5,
  PAY_CANCELED: 6,
  REJECTED: 7,
  PURCHASE_CANCELED: 8,
  BUYER_CANCEL_REQUEST: 9,
  SELLER_CANCEL_REQUEST: 10,
  REFUND_PENDING: 11, // 환불절차 진행 중
  CANCEL_FINISHED: 12, // 취소 완료
  WAITING: 20, // NOT_ACCEPTED + PREPARING + SHIPPING
  AFTER_PAY: 21, // All order list except OUTSTANDING(in cart)
};

const ORDER_STATUS_TITLE = (code) => {
  if (code === ORDER_STATUS_CODE.NOT_ACCEPTED) {
    return Strings.PAID;
  } else if (code === ORDER_STATUS_CODE.PREPARING) {
    return Strings.PREPARING_SHIPPING;
  } else if (code === ORDER_STATUS_CODE.SHIPPING) {
    return Strings.SHIPPING;
  } else if (code === ORDER_STATUS_CODE.SHIPMENT_COMPLETED) {
    return Strings.SHIPMENT_COMPLETED;
  } else if (code === ORDER_STATUS_CODE.PURCHASE_COMPLETED) {
    return Strings.PURCHASE_COMPLETED;
  } else if (code === ORDER_STATUS_CODE.REJECTED) {
    return Strings.REJECTED;
  } else if (code === ORDER_STATUS_CODE.PURCHASE_CANCELED) {
    return Strings.PURCHASE_CANCELED;
  } else if (code === ORDER_STATUS_CODE.BUYER_CANCEL_REQUEST) {
    return Strings.BUYER_CANCEL_REQUEST;
  } else if (code === ORDER_STATUS_CODE.SELLER_CANCEL_REQUEST) {
    return Strings.SELLER_CANCEL_REQUEST;
  } else if (code === ORDER_STATUS_CODE.REFUND_PENDING) {
    return Strings.REFUND_PENDING;
  } else if (code === ORDER_STATUS_CODE.CANCEL_FINISHED) {
    return Strings.CANCEL_FINISHED;
  } else {
    return '-';
  }
};

const ORDER_ACTION_CODE = {
  CANCEL: 9, // buyer
  PAY: 1, // buyer
  ACCEPT: 2, // seller
  START_SHIPMENT: 3, // seller
  END_SHIPMENT: 4, // seller
  CONFIRM_PURCHASE: 5, // buyer
  REJECT: 7, // seller
  CANCEL_PURCHASE: 8, // buyer
  BUYER_CANCEL_REQUEST: 9,
  SELLER_CANCEL_REQUEST: 10,
  ACCEPT_CANCEL_REQUEST: 11, // 관리자: 취소 수락
  REFUND_FINISHED: 12, // 관리자: 카드 취소 (환불 완료)
};

const USER_ACTION_CODE = {
  SIGNED_IN: 1,
  SIGNED_OUT: 2,
  ON_STARTED: 3,
  ON_RESUMED: 4,
  ON_PAUSED: 5,
  ON_STOPPED: 6,
  CLICKED_VIDEO_FROM_MAIN_PAGE: 100,
  CLICKED_VIDEO_FROM_RELATED_TO_VIDEO: 101,
  CLICKED_VIDEO_FROM_DISCOVER_PROMOTION: 102,
  CLICKED_VIDEO_FROM_DISCOVER_TRENDING: 103,
  CLICKED_VIDEO_FROM_DISCOVER_GREYD_PICK: 104,
  CLICKED_VIDEO_FROM_DISCOVER_CATEGORY: 105,
  CLICKED_VIDEO_FROM_DISCOVER_SEARCH: 106,
  CLICKED_VIDEO_FROM_USER_UPLOAD: 107,
  CLICKED_VIDEO_FROM_LINKED_PRODUCT: 108,
  CLICKED_PRODUCT_FROM_LINKED_VIDEO: 109,
  CLICKED_PRODUCT_FROM_STORE_PROMOTION: 110,
  CLICKED_PRODUCT_FROM_STORE_TRENDING: 111,
  CLICKED_PRODUCT_FROM_STORE_SPECIAL_PRICE: 112,
  CLICKED_PRODUCT_FROM_STORE_CATEGORY: 113,
  CLICKED_PRODUCT_FROM_STORE_SEARCH: 114,
  CLICKED_PRODUCT_RELATED_TO_PRODUCT: 115,
  CLICKED_PRODUCT_FROM_SELLER: 116,
  CLICKED_PRODUCT_FROM_USER_UPLOAD: 117,
  SHARE_VIDEO_OUT: 150,
  ELAPSED_TIME_VIDEO_WATCHING: 200,
  ELAPSED_TIME_PRODUCT_VIEWING: 201,
};

const NOTIFICATION_CODE = {
  SERVER_SIDE_NOTIFICATION: 0,

  NEW_RATING_ON_UPLOADED_VIDEO: 101,
  NEW_REVIEW_ON_UPLOADED_PRODUCT: 102,
  NEW_COMMENT_ON_UPLOADED_VIDEO: 103,
  NEW_COMMENT_ON_UPLOADED_PRODUCT: 104,
  NEW_BOOKMARK_ON_UPLOADED_VIDEO: 105,
  NEW_BOOKMARK_ON_UPLOADED_PRODUCT: 106,
  NEW_LINKED_VIDEO_ON_UPLOADED_PRODUCT: 107,
  NEW_FOLLOWER: 110,
  NEW_RELAY_REVIEW_ON_UPLOADED_REVIEW: 112,
  NEW_COMMENT_ON_TAGGED_USER: 191,
  NEW_NESTED_COMMENT_ON_COMMENT: 192,
  NEW_COMMENT_ON_UPLOADED_REVIEW_YOU_COMMENTED: 199,
  ORDER_NOT_ACCEPTED: 202,
  ORDER_PREPARING: 203,
  ORDER_SHIPPING: 204,
  ORDER_SHIPMENT_COMPLETED: 205,
  ORDER_PURCHASE_COMPLETED: 206,
  ORDER_REJECTED: 207,
  ORDER_PURCHASE_CANCELED: 208,
  ORDER_PURCHASE_COMPLETED_AUTOMATICALLY: 209,
  ORDER_CANCEL_REQUEST_BY_BUYER: 210,
  ORDER_CANCEL_REQUEST_BY_SELLER: 211,
  ORDER_CANCEL_PENDING_BY_ADMIN: 212,
  ORDER_CANCEL_FINISHED: 213,
  // Push messages to reviewers after User purchase an item through a review
  ORDER_PURCHASE_ALARM_TO_REVIEWER: 214,
  USER_WITHDRAWAL_ACCEPTED: 301,
  USER_WITHDRAWAL_REJECTED: 302,
  USER_WITHDRAWAL_FINISHED: 303,
  // REVIEW_REWARD_FUNDED: 301,
  // REVIEW_REWARD_WITHDRAWAL: 302,
  APPROVAL_SELLER_REGISTER: 401,
  QNA_HASHTAG_CREATED: 501,
  QNA_CHAT_CREATED: 502,
  QNA_CHAT_MENTIONED: 503,
  REVIEWER_REQUESTED_WITHDRAWAL: 900,
};

const PAYMENT_METHOD_CODE = {
  CREDIT_CARD: 1,
};

//Product attachment change code
const ATTACHMENT_CHANGE_ADDED = 1;
const ATTACHMENT_CHANGE_REMOVED = 2;

const NOTIFICATION_CHENNEL_ID = 'greyd-chennel-main-id';
const NOTIFICATION_CHENNEL_NAME = 'greyd-chennel';

const REPORT_REASON_CODE = {
  SEXUAL_REVIEW: 1,
  VIOLENT_REVIEW: 2,
  MALICIOUS_REVIEW: 3,
  HARASSMENT_REVIEW: 4,
  INJURIOUS_REVIEW: 5,
  INVALID_REVIEW: 6,
  SEXUAL_PRODUCT: 101,
  VIOLENT_PRODUCT: 102,
  DRUGWEAPON_PRODUCT: 103,
  ILLEGAL_PRODUCT: 104,
  INJURIOUS_PRODUCT: 105,
  UNAVAILABLE_PRODUCT: 106,
  INVALID_PRODUCT: 107,
  HARASSMENT_USER: 201,
  PRIVACY_USER: 202,
  IMPERSONATION_USER: 203,
  VIOLENT_USER: 204,
  CHILDABUSE_USER: 205,
  HATESPEECH_USER: 206,
  SPAM_USER: 207,
  OTHERS_USER: 208,
  CHILDABUSE_COMMENT: 301, // 아동학대
  SEXUAL_COMMENT: 302, // 음란물
  SPAM_COMMENT: 303, // 상업성 또는 스팸
  VIOLENT_COMMENT: 304, // 폭력적 또는 혐오스러운 콘텐츠
  MALICIOUS_COMMENT: 305, // 증오 또는 악의적인 콘텐츠
  HARASSMENT_COMMENT: 306, // 괴롭힘 및 사이버폭력
  INJURIOUS_COMMENT: 307, // 유해하거나 위험한 행위
  INVALID_COMMENT: 308, // 부적절한 댓글
};

const NOTICE_CODE = {
  LAUNCH_PROMOTION: 1,
  GRADING_REVIEW_PROMOTION_1: 2,
  GRADING_REVIEW_PROMOTION_RESULT_1: 3,
};

const UPLOADING_VIDEO_STATE = {
  STANDBY: 'standby',
  UPLOADING: 'uploading',
  UPLOADED: 'uploaded',
  ENCODING: 'encoding',
  ERROR: 'error',
  STOPPED: 'stopped',
};

const VIDEO_LIST_SORT_TYPE = {
  RECENT: 'recent',
  VIEW: 'view',
  SCORE: 'score',
  RECOMMEND: 'recommend',
  NOT_RECOMMEND: 'not_recommend',
};

const PRODUCT_LIST_SORT_TYPE = {
  RECENT: 'recent',
  SELL_COUNT: 'sell_count',
  DISCOUNT_RATE: 'discount_rate',
  REVIEW_COUNT: 'review_count',
};

const USER_LIST_SORT_TYPE = {
  RECENT_ACCOUNT_CREATED: 'RECENT_ACCOUNT_CREATED',
  RECENT_REVIEW_UPLOADED: 'RECENT_REVIEW_UPLOADED',
  VIEW_COUNT: 'VIEW_COUNT',
  REVENUE_AMOUNT: 'REVENUE_AMOUNT',
  SCORE: 'SCORE',
  REVIEW_COUNT: 'REVIEW_COUNT',
};

const USER_LIST_LATEST_RECOMMENDED = 'RISING';

const WITHDRAWAL_STATUS_CODE = {
  REQUESTED: 'REQUESTED',
  ACCEPTED: 'ACCEPTED',
  FINISHED: 'FINISHED',
  REJECTED: 'REJECTED',
};

const BANK_LIST = [
  { key: 'agency', title: Strings.BANK_AGENCY },
  { key: 'paypal', title: Strings.BANK_PAYPAL },
  { key: 'keb', title: Strings.BANK_KEB },
  { key: 'sc', title: Strings.BANK_SC },
  { key: 'kb', title: Strings.BANK_KB },
  { key: 'shinhan', title: Strings.BANK_SHINHAN },
  { key: 'woori', title: Strings.BANK_WOORI },
  { key: 'citi', title: Strings.BANK_CITI },
  { key: 'ibk', title: Strings.BANK_IBK },
  { key: 'nh', title: Strings.BANK_NH },
  { key: 'suhyup', title: Strings.BANK_SUHYUP },
  { key: 'etc', title: Strings.BANK_ETC },
];

const COURIER_LIST = [
  { key: 'cj', title: 'CJ대한통운' },
  { key: 'hanjin', title: '한진택배' },
  { key: 'lotte', title: '롯데택배' },
  { key: 'post', title: '우체국택배' },
  { key: 'logen', title: '로젠택배' },
  { key: 'cu', title: 'CU 편의점택배' },
  { key: 'gs', title: 'GS Postbox' },
  { key: 'etc', title: '직접 입력' },
];

const SELLER_STATUS = {
  APPROVAL_REQUEST: 'APPROVAL_REQUEST',
  APPROVED: 'APPROVED',
};

const COUNTRY = {
  KOREA: 'Korea',
  US: 'US',
};

const REWARD_TYPE = {
  REWARD: 'REWARD',
  EVENT_REWARD: 'EVENT_REWARD',
  CERTIFIED_REVIEWER_REWARD: 'CERTIFIED_REVIEWER_REWARD',
  WITHDRAWAL: 'WITHDRAWAL',
  POINT: {
    REVIEW: 'REVIEW',
    GRADE: 'GRADE',
    COMMENT: 'COMMENT',
    ATTENDANCE: 'ATTENDANCE',
  },
  DEDUCT: 'DEDUCT',
  ROLLBACK: 'ROLLBACK',
  BUY_REWARD: 'BUY_REWARD',
};

const CART_FROM = {
  CART: 'CART',
  BUY: 'BUY',
};

const KOVAN_PAY_GROUP = {
  CREDIT_CARD: 'GEP',
  KAKAO_PAY: 'KKP',
  NAVER_PAY: 'NVP',
};

const KOVAN_PAY_METHOD = {
  CREDIT_CARD: 'CC',
  VIRTUAL_ACCOUNT: 'VA',
  BANK_ACCOUNT: 'BA',
  SIMPLE_PAY: 'VO',
};

const PAGE_SCREEN_NAMES = [
  'VideoGuide',
  'TierGuide',
  'G6Guide',
  'VideoPage',
  'VideoList',
  'AddingNewVideo',
  'Search',
  'Notification',
  'BlockedUserList',
  'SearchProduct',
  'ProductPage',
  'ProductList',
  'AddingNewProduct',
  'UserPage',
  'B2BPage',
  'B2BProductList',
  'UserList',
  'FollowList',
  'Settings',
  'OrderPage',
  'OrderList',
  'MyOrderList',
  'Cart',
  'BookmarkList',
  'RewardList',
  'MyStore',
  'RegisterAsSeller',
  'QRCode',
  'ChatView',
  'QNAChat',
  'G6UserChart',
];

// B2B 네비게이터(B2B) 하위 스크린 — 밖에서 이동할 땐 nested navigate('B2B', {screen, params}) 필요
const B2B_SCREEN_NAMES = ['B2BPage', 'B2BProductList', 'B2BProductPage', 'B2BProductInquiry'];

const HELP_BUBBLE_PAGE_KEY = {
  MAIN: 'main',
  VIDEO: 'video',
  ADDING_NEW_VIDEO: 'addingNewVideo',
  TIER_GUIDE: 'tierGuide',
};

const REGION_TO_LANGUAGE = {
  KR: 'ko',
  US: 'en',
  ES: 'es',
  JP: 'ja',
  RU: 'ru',
  FR: 'fr',
};

export default {
  NOTICE_CODE,
  REPORT_REASON_CODE,
  POST_STATUS_CODE,
  USER_STATUS_CODE,
  ORDER_STATUS_CODE,
  USER_LIST_SORT_TYPE,
  ORDER_STATUS_TITLE,
  ORDER_ACTION_CODE,
  USER_ACTION_CODE,
  PAYMENT_METHOD_CODE,
  ATTACHMENT_CHANGE_ADDED,
  ATTACHMENT_CHANGE_REMOVED,
  NOTIFICATION_CODE,
  NOTIFICATION_CHENNEL_ID,
  NOTIFICATION_CHENNEL_NAME,
  UPLOADING_VIDEO_STATE,
  VIDEO_LIST_SORT_TYPE,
  PRODUCT_LIST_SORT_TYPE,
  BANK_LIST,
  COURIER_LIST,
  WITHDRAWAL_STATUS_CODE,
  USER_LIST_LATEST_RECOMMENDED,
  SELLER_STATUS,
  COUNTRY,
  REWARD_TYPE,
  CART_FROM,
  KOVAN_PAY_GROUP,
  KOVAN_PAY_METHOD,
  PAGE_SCREEN_NAMES,
  B2B_SCREEN_NAMES,
  HELP_BUBBLE_PAGE_KEY,
  REGION_TO_LANGUAGE,
};
