const VIBRATION_USER_ACTION = 20;

const MAX_VIDEO_LENGTH = 300;
const MAX_SIZE_VIDEO = 200 * 1024 * 1024;
const MAX_SCALE_VIDEO = 1920;
const MAX_SCALE_REVIEW_IMAGE = 1920;
const MAX_SCALE_USER_PROFILE_PIC = 512;
const MAX_SCALE_PRODUCT_IMAGE = 1080;
const MAX_SCALE_CERTIFICATION_IMAGE = 1920;
const MIN_LENGTH_USER_ID = 3;
const MAX_LENGTH_USER_ID = 16;
const MAX_LENGTH_USER_NAME = 40;
const MAX_LENGTH_USER_PHONE = 20;
const MAX_LENGTH_USER_EMAIL = 50;
const MAX_LENGTH_PRODUCT_TITLE = 100;
const MAX_LENGTH_PRODUCT_DESCRIPTION = 800;
const MAX_LENGTH_REVIEW_TITLE = 100;
const MAX_LENGTH_REVIEW_DESCRIPTION = 800;
const MAX_LENGTH_USER_INTRODUCTION = 100;
const MAX_LENGTH_ORDER_MEMO = 800;
const MAX_LENGTH_ADDRESS = 200;
const MAX_LENGTH_URL = 200;
const MAX_LENGTH_SELLER_CERTIFICATION_NO = 20;
const MAX_NUMBER_REVIEW_IMAGE = 5;
const MAX_NUMBER_PRODUCT_IMAGE = 10;
const MAX_NUMBER_PRODUCT_DESCRIPTION_IMAGE = 10;
const MAX_SCALE_PRODUCT_DESCRIPTION_IMAGE_WIDTH = 1000;
const MAX_SCALE_PRODUCT_DESCRIPTION_IMAGE_HEIGHT = 20000;
const PRODUCT_DESCRIPTION_IMAGE_HEIGHT_UNIT_ANDROID = 15000;

const HIGHLIGHT_SECONDS = 5;

const KRW_PER_USD = 1180;

export default {
  VIBRATION_USER_ACTION,
  MAX_VIDEO_LENGTH,
  MAX_SIZE_VIDEO,
  MAX_SCALE_VIDEO,
  MAX_SCALE_REVIEW_IMAGE,
  MAX_SCALE_USER_PROFILE_PIC,
  MAX_SCALE_PRODUCT_IMAGE,
  MAX_SCALE_CERTIFICATION_IMAGE,
  MAX_NUMBER_REVIEW_IMAGE,
  MAX_NUMBER_PRODUCT_IMAGE,
  MAX_NUMBER_PRODUCT_DESCRIPTION_IMAGE,
  MAX_SCALE_PRODUCT_DESCRIPTION_IMAGE_WIDTH,
  MAX_SCALE_PRODUCT_DESCRIPTION_IMAGE_HEIGHT,
  PRODUCT_DESCRIPTION_IMAGE_HEIGHT_UNIT_ANDROID,
  MIN_LENGTH_USER_ID,
  MAX_LENGTH_USER_ID,
  MAX_LENGTH_USER_NAME,
  MAX_LENGTH_USER_PHONE,
  MAX_LENGTH_USER_EMAIL,
  MAX_LENGTH_PRODUCT_TITLE,
  MAX_LENGTH_PRODUCT_DESCRIPTION,
  MAX_LENGTH_REVIEW_TITLE,
  MAX_LENGTH_REVIEW_DESCRIPTION,
  MAX_LENGTH_USER_INTRODUCTION,
  MAX_LENGTH_ORDER_MEMO,
  MAX_LENGTH_ADDRESS,
  MAX_LENGTH_URL,
  MAX_LENGTH_SELLER_CERTIFICATION_NO,
  HIGHLIGHT_SECONDS,
  KRW_PER_USD,
};
