// export const nationalities = {
//   AF: { ko: '아프가니스탄', en: 'Afghanistan' },
//   AL: { ko: '알바니아', en: 'Albania' },
//   DZ: { ko: '알제리', en: 'Algeria' },
//   AS: { ko: '아메리칸사모아', en: 'American Samoa' },
//   AD: { ko: '안도라', en: 'Andorra' },
//   AO: { ko: '앙골라', en: 'Angola' },
//   AI: { ko: '앵귈라', en: 'Anguilla' },
//   AQ: { ko: '남극', en: 'Antarctica' },
//   AG: { ko: '앤티가 바부다', en: 'Antigua and Barbuda' },
//   AR: { ko: '아르헨티나', en: 'Argentina' },
//   AM: { ko: '아르메니아', en: 'Armenia' },
//   AW: { ko: '아루바', en: 'Aruba' },
//   AU: { ko: '호주', en: 'Australia' },
//   AT: { ko: '오스트리아', en: 'Austria' },
//   AZ: { ko: '아제르바이잔', en: 'Azerbaijan' },
//   BS: { ko: '바하마', en: 'Bahamas' },
//   BH: { ko: '바레인', en: 'Bahrain' },
//   BD: { ko: '방글라데시', en: 'Bangladesh' },
//   BB: { ko: '바베이도스', en: 'Barbados' },
//   BY: { ko: '벨라루스', en: 'Belarus' },
//   BE: { ko: '벨기에', en: 'Belgium' },
//   BZ: { ko: '벨리즈', en: 'Belize' },
//   BJ: { ko: '베냉', en: 'Benin' },
//   BM: { ko: '버뮤다', en: 'Bermuda' },
//   BT: { ko: '부탄', en: 'Bhutan' },
//   BO: { ko: '볼리비아', en: 'Bolivia' },
//   BA: { ko: '보스니아 헤르체고비나', en: 'Bosnia and Herzegovina' },
//   BW: { ko: '보츠와나', en: 'Botswana' },
//   BV: { ko: '부베 섬', en: 'Bouvet Island' },
//   BR: { ko: '브라질', en: 'Brazil' },
//   IO: { ko: '인도', en: 'British Indian Ocean Territory' },
//   VG: { ko: '영국령 버진아일랜드', en: 'British Virgin Islands' },
//   BN: { ko: '브루나이', en: 'Brunei' },
//   BG: { ko: '불가리아', en: 'Bulgaria' },
//   BF: { ko: '부르키나파소', en: 'Burkina Faso' },
//   BI: { ko: '부룬디', en: 'Burundi' },
//   KH: { ko: '캄보디아', en: 'Cambodia' },
//   CM: { ko: '카메룬', en: 'Cameroon' },
//   CA: { ko: '캐나다', en: 'Canada' },
//   CV: { ko: '카보베르데', en: 'Cape Verde' },
//   BQ: { ko: '카리브 네덜란드', en: 'Caribbean Netherlands' },
//   KY: { ko: '케이맨 제도', en: 'Cayman Islands' },
//   CF: { ko: '중앙아프리카 공화국', en: 'Central African Republic' },
//   TD: { ko: '차드', en: 'Chad' },
//   CL: { ko: '칠레', en: 'Chile' },
//   CN: { ko: '중국', en: 'China' },
//   CX: { ko: '크리스마스 섬', en: 'Christmas Island' },
//   CC: { ko: '코코스 제도', en: 'Cocos (Keeling) Islands' },
//   CO: { ko: '콜롬비아', en: 'Colombia' },
//   KM: { ko: '코모로', en: 'Comoros' },
//   CK: { ko: '쿡 제도', en: 'Cook Islands' },
//   CR: { ko: '코스타리카', en: 'Costa Rica' },
//   HR: { ko: '크로아티아', en: 'Croatia' },
//   CU: { ko: '쿠바', en: 'Cuba' },
//   CW: { ko: '퀴라소', en: 'Curaçao' },
//   CY: { ko: '키프로스', en: 'Cyprus' },
//   CZ: { ko: '체코', en: 'Czechia' },
//   CD: { ko: '콩고 민주 공화국', en: 'DR Congo' },
//   DK: { ko: '덴마크', en: 'Denmark' },
//   DJ: { ko: '지부티', en: 'Djibouti' },
//   DM: { ko: '도미니카 공화국', en: 'Dominica' },
//   DO: { ko: '도미니카 공화국', en: 'Dominican Republic' },
//   EC: { ko: '에콰도르', en: 'Ecuador' },
//   EG: { ko: '이집트', en: 'Egypt' },
//   SV: { ko: '엘살바도르', en: 'El Salvador' },
//   GQ: { ko: '적도 기니', en: 'Equatorial Guinea' },
//   ER: { ko: '에리트레아', en: 'Eritrea' },
//   EE: { ko: '에스토니아', en: 'Estonia' },
//   SZ: { ko: '에스와티니', en: 'Eswatini' },
//   ET: { ko: '에티오피아', en: 'Ethiopia' },
//   FK: { ko: '포클랜드 제도', en: 'Falkland Islands' },
//   FO: { ko: '페로 제도', en: 'Faroe Islands' },
//   FJ: { ko: '피지', en: 'Fiji' },
//   FI: { ko: '핀란드', en: 'Finland' },
//   FR: { ko: '프랑스', en: 'France' },
//   GF: { ko: '프랑스령 기아나', en: 'French Guiana' },
//   PF: { ko: '프랑스령 폴리네시아', en: 'French Polynesia' },
//   TF: { ko: '프랑스령 남부와 남극 지역', en: 'French Southern and Antarctic Lands' },
//   GA: { ko: '가봉', en: 'Gabon' },
//   GM: { ko: '감비아', en: 'Gambia' },
//   GE: { ko: '조지아', en: 'Georgia' },
//   DE: { ko: '독일', en: 'Germany' },
//   GH: { ko: '가나', en: 'Ghana' },
//   GI: { ko: '지브롤터', en: 'Gibraltar' },
//   GR: { ko: '그리스', en: 'Greece' },
//   GL: { ko: '그린란드', en: 'Greenland' },
//   GD: { ko: '그레나다', en: 'Grenada' },
//   GP: { ko: '과들루프', en: 'Guadeloupe' },
//   GU: { ko: '괌', en: 'Guam' },
//   GT: { ko: '과테말라', en: 'Guatemala' },
//   GG: { ko: '건지 섬', en: 'Guernsey' },
//   GN: { ko: '기니', en: 'Guinea' },
//   GW: { ko: '기니비사우', en: 'Guinea-Bissau' },
//   GY: { ko: '가이아나', en: 'Guyana' },
//   HT: { ko: '아이티', en: 'Haiti' },
//   HM: { ko: '허드 맥도널드 제도', en: 'Heard Island and McDonald Islands' },
//   HN: { ko: '온두라스', en: 'Honduras' },
//   HK: { ko: '홍콩', en: 'Hong Kong' },
//   HU: { ko: '헝가리', en: 'Hungary' },
//   IS: { ko: '아이슬란드', en: 'Iceland' },
//   IN: { ko: '인도', en: 'India' },
//   ID: { ko: '인도네시아', en: 'Indonesia' },
//   IR: { ko: '이란', en: 'Iran' },
//   IQ: { ko: '이라크', en: 'Iraq' },
//   IE: { ko: '아일랜드', en: 'Ireland' },
//   IM: { ko: '맨섬', en: 'Isle of Man' },
//   IL: { ko: '이스라엘', en: 'Israel' },
//   IT: { ko: '이탈리아', en: 'Italy' },
//   CI: { ko: '코트디부아르', en: 'Ivory Coast' },
//   JM: { ko: '자메이카', en: 'Jamaica' },
//   JP: { ko: '일본', en: 'Japan' },
//   JE: { ko: '저지 섬', en: 'Jersey' },
//   JO: { ko: '요르단', en: 'Jordan' },
//   KZ: { ko: '카자흐스탄', en: 'Kazakhstan' },
//   KE: { ko: '케냐', en: 'Kenya' },
//   KI: { ko: '키리바시', en: 'Kiribati' },
//   XK: { ko: '코소보', en: 'Kosovo' },
//   KW: { ko: '쿠웨이트', en: 'Kuwait' },
//   KG: { ko: '키르기스스탄', en: 'Kyrgyzstan' },
//   LA: { ko: '라오스', en: 'Laos' },
//   LV: { ko: '라트비아', en: 'Latvia' },
//   LB: { ko: '레바논', en: 'Lebanon' },
//   LS: { ko: '레소토', en: 'Lesotho' },
//   LR: { ko: '라이베리아', en: 'Liberia' },
//   LY: { ko: '리비아', en: 'Libya' },
//   LI: { ko: '리히텐슈타인', en: 'Liechtenstein' },
//   LT: { ko: '리투아니아', en: 'Lithuania' },
//   LU: { ko: '룩셈부르크', en: 'Luxembourg' },
//   MO: { ko: '마카오', en: 'Macau' },
//   MK: { ko: '마케도니아', en: 'Macedonia' },
//   MG: { ko: '마다가스카르', en: 'Madagascar' },
//   MW: { ko: '말라위', en: 'Malawi' },
//   MY: { ko: '말레이시아', en: 'Malaysia' },
//   MV: { ko: '몰디브', en: 'Maldives' },
//   ML: { ko: '말리', en: 'Mali' },
//   MT: { ko: '몰타', en: 'Malta' },
//   MH: { ko: '마셜 제도', en: 'Marshall Islands' },
//   MQ: { ko: '마르티니크', en: 'Martinique' },
//   MR: { ko: '모리타니', en: 'Mauritania' },
//   MU: { ko: '모리셔스', en: 'Mauritius' },
//   YT: { ko: '마요트', en: 'Mayotte' },
//   MX: { ko: '멕시코', en: 'Mexico' },
//   FM: { ko: '미크로네시아', en: 'Micronesia' },
//   MD: { ko: '몰도바', en: 'Moldova' },
//   MC: { ko: '모나코', en: 'Monaco' },
//   MN: { ko: '몽골국', en: 'Mongolia' },
//   ME: { ko: '몬테네그로', en: 'Montenegro' },
//   MS: { ko: '몬트세랫', en: 'Montserrat' },
//   MA: { ko: '모로코', en: 'Morocco' },
//   MZ: { ko: '모잠비크', en: 'Mozambique' },
//   MM: { ko: '미얀마', en: 'Myanmar' },
//   NA: { ko: '나미비아', en: 'Namibia' },
//   NR: { ko: '나우루', en: 'Nauru' },
//   NP: { ko: '네팔', en: 'Nepal' },
//   NL: { ko: '네덜란드', en: 'Netherlands' },
//   NC: { ko: '누벨칼레도니', en: 'New Caledonia' },
//   NZ: { ko: '뉴질랜드', en: 'New Zealand' },
//   NI: { ko: '니카라과', en: 'Nicaragua' },
//   NE: { ko: '니제르', en: 'Niger' },
//   NG: { ko: '나이지리아', en: 'Nigeria' },
//   NU: { ko: '니우에', en: 'Niue' },
//   NF: { ko: '노퍽 섬', en: 'Norfolk Island' },
//   KP: { ko: '조선', en: 'North Korea' },
//   MP: { ko: '북마리아나 제도', en: 'Northern Mariana Islands' },
//   NO: { ko: '노르웨이', en: 'Norway' },
//   OM: { ko: '오만', en: 'Oman' },
//   PK: { ko: '파키스탄', en: 'Pakistan' },
//   PW: { ko: '팔라우', en: 'Palau' },
//   PS: { ko: '팔레스타인', en: 'Palestine' },
//   PA: { ko: '파나마', en: 'Panama' },
//   PG: { ko: '파푸아뉴기니', en: 'Papua New Guinea' },
//   PY: { ko: '파라과이', en: 'Paraguay' },
//   PE: { ko: '페루', en: 'Peru' },
//   PH: { ko: '필리핀', en: 'Philippines' },
//   PN: { ko: '핏케언 제도', en: 'Pitcairn Islands' },
//   PL: { ko: '폴란드', en: 'Poland' },
//   PT: { ko: '포르투갈', en: 'Portugal' },
//   PR: { ko: '푸에르토리코', en: 'Puerto Rico' },
//   QA: { ko: '카타르', en: 'Qatar' },
//   CG: { ko: '콩고', en: 'Republic of the Congo' },
//   RO: { ko: '루마니아', en: 'Romania' },
//   RU: { ko: '러시아', en: 'Russia' },
//   RW: { ko: '르완다', en: 'Rwanda' },
//   RE: { ko: '레위니옹', en: 'Réunion' },
//   BL: { ko: '생바르텔레미', en: 'Saint Barthélemy' },
//   SH: { ko: '세인트헬레나', en: 'Saint Helena, Ascension and Tristan da Cunha' },
//   KN: { ko: '세인트키츠 네비스', en: 'Saint Kitts and Nevis' },
//   LC: { ko: '세인트루시아', en: 'Saint Lucia' },
//   MF: { ko: '생마르탱', en: 'Saint Martin' },
//   PM: { ko: '생피에르 미클롱', en: 'Saint Pierre and Miquelon' },
//   VC: { ko: '세인트빈센트 그레나딘', en: 'Saint Vincent and the Grenadines' },
//   WS: { ko: '사모아', en: 'Samoa' },
//   SM: { ko: '산마리노', en: 'San Marino' },
//   SA: { ko: '사우디아라비아', en: 'Saudi Arabia' },
//   SN: { ko: '세네갈', en: 'Senegal' },
//   RS: { ko: '세르비아', en: 'Serbia' },
//   SC: { ko: '세이셸', en: 'Seychelles' },
//   SL: { ko: '시에라리온', en: 'Sierra Leone' },
//   SG: { ko: '싱가포르', en: 'Singapore' },
//   SX: { ko: '신트마르턴', en: 'Sint Maarten' },
//   SK: { ko: '슬로바키아', en: 'Slovakia' },
//   SI: { ko: '슬로베니아', en: 'Slovenia' },
//   SB: { ko: '솔로몬 제도', en: 'Solomon Islands' },
//   SO: { ko: '소말리아', en: 'Somalia' },
//   ZA: { ko: '남아프리카', en: 'South Africa' },
//   GS: { ko: '조지아', en: 'South Georgia' },
//   KR: { ko: '한국', en: 'South Korea' },
//   SS: { ko: '남수단', en: 'South Sudan' },
//   ES: { ko: '스페인', en: 'Spain' },
//   LK: { ko: '스리랑카', en: 'Sri Lanka' },
//   SD: { ko: '수단', en: 'Sudan' },
//   SR: { ko: '수리남', en: 'Suriname' },
//   SJ: { ko: '스발바르 얀마옌 제도', en: 'Svalbard and Jan Mayen' },
//   SE: { ko: '스웨덴', en: 'Sweden' },
//   CH: { ko: '스위스', en: 'Switzerland' },
//   SY: { ko: '시리아', en: 'Syria' },
//   ST: { ko: '상투메 프린시페', en: 'São Tomé and Príncipe' },
//   TW: { ko: '대만', en: 'Taiwan' },
//   TJ: { ko: '타지키스탄', en: 'Tajikistan' },
//   TZ: { ko: '탄자니아', en: 'Tanzania' },
//   TH: { ko: '태국', en: 'Thailand' },
//   TL: { ko: '동티모르', en: 'Timor-Leste' },
//   TG: { ko: '토고', en: 'Togo' },
//   TK: { ko: '토켈라우', en: 'Tokelau' },
//   TO: { ko: '통가', en: 'Tonga' },
//   TT: { ko: '트리니다드 토바고', en: 'Trinidad and Tobago' },
//   TN: { ko: '튀니지', en: 'Tunisia' },
//   TR: { ko: '터키', en: 'Turkey' },
//   TM: { ko: '투르크메니스탄', en: 'Turkmenistan' },
//   TC: { ko: '터크스 케이커스 제도', en: 'Turks and Caicos Islands' },
//   TV: { ko: '투발루', en: 'Tuvalu' },
//   UG: { ko: '우간다', en: 'Uganda' },
//   UA: { ko: '우크라이나', en: 'Ukraine' },
//   AE: { ko: '아랍에미리트', en: 'United Arab Emirates' },
//   GB: { ko: '영국', en: 'United Kingdom' },
//   US: { ko: '미국', en: 'United States' },
//   UM: { ko: '미국령 군소 제도', en: 'United States Minor Outlying Islands' },
//   VI: { ko: '미국령 버진아일랜드', en: 'United States Virgin Islands' },
//   UY: { ko: '우루과이', en: 'Uruguay' },
//   UZ: { ko: '우즈베키스탄', en: 'Uzbekistan' },
//   VU: { ko: '바누아투', en: 'Vanuatu' },
//   VA: { ko: '바티칸', en: 'Vatican City' },
//   VE: { ko: '베네수엘라', en: 'Venezuela' },
//   VN: { ko: '베트남', en: 'Vietnam' },
//   WF: { ko: '왈리스 푸투나', en: 'Wallis and Futuna' },
//   EH: { ko: '서사하라', en: 'Western Sahara' },
//   YE: { ko: '예멘', en: 'Yemen' },
//   ZM: { ko: '잠비아', en: 'Zambia' },
//   ZW: { ko: '짐바브웨', en: 'Zimbabwe' },
//   AX: { ko: '올란드 제도', en: 'Åland Islands' },
// };

// Object.keys(b).forEach(n => {
//   Object.keys(a).forEach(n2 => {
//       if(n === n2) {
//           b[n]['code'] = a[n2];
//       }
//   });
// });

export const nationalities = {
  AF: { ko: '아프가니스탄', en: 'Afghanistan', code: 'AFG' },
  AL: { ko: '알바니아', en: 'Albania', code: 'ALB' },
  DZ: { ko: '알제리', en: 'Algeria', code: 'DZA' },
  AS: { ko: '아메리칸사모아', en: 'American Samoa' },
  AD: { ko: '안도라', en: 'Andorra', code: 'AND' },
  AO: { ko: '앙골라', en: 'Angola', code: 'AGO' },
  AI: { ko: '앵귈라', en: 'Anguilla' },
  AQ: { ko: '남극', en: 'Antarctica' },
  AG: { ko: '앤티가 바부다', en: 'Antigua and Barbuda', code: 'ATG' },
  AR: { ko: '아르헨티나', en: 'Argentina', code: 'ARG' },
  AM: { ko: '아르메니아', en: 'Armenia', code: 'ARM' },
  AW: { ko: '아루바', en: 'Aruba' },
  AU: { ko: '호주', en: 'Australia', code: 'AUS' },
  AT: { ko: '오스트리아', en: 'Austria', code: 'AUT' },
  AZ: { ko: '아제르바이잔', en: 'Azerbaijan', code: 'AZE' },
  BS: { ko: '바하마', en: 'Bahamas', code: 'BHS' },
  BH: { ko: '바레인', en: 'Bahrain', code: 'BHR' },
  BD: { ko: '방글라데시', en: 'Bangladesh', code: 'BGD' },
  BB: { ko: '바베이도스', en: 'Barbados', code: 'BRB' },
  BY: { ko: '벨라루스', en: 'Belarus', code: 'BLR' },
  BE: { ko: '벨기에', en: 'Belgium', code: 'BEL' },
  BZ: { ko: '벨리즈', en: 'Belize', code: 'BLZ' },
  BJ: { ko: '베냉', en: 'Benin', code: 'BEN' },
  BM: { ko: '버뮤다', en: 'Bermuda' },
  BT: { ko: '부탄', en: 'Bhutan', code: 'BTN' },
  BO: { ko: '볼리비아', en: 'Bolivia', code: 'BOL' },
  BA: { ko: '보스니아 헤르체고비나', en: 'Bosnia and Herzegovina', code: 'BIH' },
  BW: { ko: '보츠와나', en: 'Botswana', code: 'BWA' },
  BV: { ko: '부베 섬', en: 'Bouvet Island' },
  BR: { ko: '브라질', en: 'Brazil', code: 'BRA' },
  IO: { ko: '인도', en: 'British Indian Ocean Territory' },
  VG: { ko: '영국령 버진아일랜드', en: 'British Virgin Islands' },
  BN: { ko: '브루나이', en: 'Brunei', code: 'BRN' },
  BG: { ko: '불가리아', en: 'Bulgaria', code: 'BGR' },
  BF: { ko: '부르키나파소', en: 'Burkina Faso', code: 'BFA' },
  BI: { ko: '부룬디', en: 'Burundi', code: 'BDI' },
  KH: { ko: '캄보디아', en: 'Cambodia', code: 'KHM' },
  CM: { ko: '카메룬', en: 'Cameroon', code: 'CMR' },
  CA: { ko: '캐나다', en: 'Canada', code: 'CAN' },
  CV: { ko: '카보베르데', en: 'Cape Verde', code: 'CPV' },
  BQ: { ko: '카리브 네덜란드', en: 'Caribbean Netherlands' },
  KY: { ko: '케이맨 제도', en: 'Cayman Islands' },
  CF: { ko: '중앙아프리카 공화국', en: 'Central African Republic', code: 'CAF' },
  TD: { ko: '차드', en: 'Chad', code: 'TCD' },
  CL: { ko: '칠레', en: 'Chile', code: 'CHL' },
  CN: { ko: '중국', en: 'China', code: 'CHN' },
  CX: { ko: '크리스마스 섬', en: 'Christmas Island' },
  CC: { ko: '코코스 제도', en: 'Cocos (Keeling) Islands' },
  CO: { ko: '콜롬비아', en: 'Colombia', code: 'COL' },
  KM: { ko: '코모로', en: 'Comoros', code: 'COM' },
  CK: { ko: '쿡 제도', en: 'Cook Islands', code: 'COK' },
  CR: { ko: '코스타리카', en: 'Costa Rica', code: 'CRI' },
  HR: { ko: '크로아티아', en: 'Croatia', code: 'HRV' },
  CU: { ko: '쿠바', en: 'Cuba', code: 'CUB' },
  CW: { ko: '퀴라소', en: 'Curaçao' },
  CY: { ko: '키프로스', en: 'Cyprus', code: 'CYP' },
  CZ: { ko: '체코', en: 'Czechia', code: 'CZE' },
  CD: { ko: '콩고 민주 공화국', en: 'DR Congo', code: 'COD' },
  DK: { ko: '덴마크', en: 'Denmark', code: 'DNK' },
  DJ: { ko: '지부티', en: 'Djibouti', code: 'DJI' },
  DM: { ko: '도미니카 공화국', en: 'Dominica', code: 'DMA' },
  DO: { ko: '도미니카 공화국', en: 'Dominican Republic', code: 'DOM' },
  EC: { ko: '에콰도르', en: 'Ecuador', code: 'ECU' },
  EG: { ko: '이집트', en: 'Egypt', code: 'EGY' },
  SV: { ko: '엘살바도르', en: 'El Salvador', code: 'SLV' },
  GQ: { ko: '적도 기니', en: 'Equatorial Guinea', code: 'GNQ' },
  ER: { ko: '에리트레아', en: 'Eritrea', code: 'ERI' },
  EE: { ko: '에스토니아', en: 'Estonia', code: 'EST' },
  SZ: { ko: '에스와티니', en: 'Eswatini', code: 'SWZ' },
  ET: { ko: '에티오피아', en: 'Ethiopia', code: 'ETH' },
  FK: { ko: '포클랜드 제도', en: 'Falkland Islands' },
  FO: { ko: '페로 제도', en: 'Faroe Islands' },
  FJ: { ko: '피지', en: 'Fiji', code: 'FJI' },
  FI: { ko: '핀란드', en: 'Finland', code: 'FIN' },
  FR: { ko: '프랑스', en: 'France', code: 'FRA' },
  GF: { ko: '프랑스령 기아나', en: 'French Guiana' },
  PF: { ko: '프랑스령 폴리네시아', en: 'French Polynesia' },
  TF: { ko: '프랑스령 남부와 남극 지역', en: 'French Southern and Antarctic Lands' },
  GA: { ko: '가봉', en: 'Gabon', code: 'GAB' },
  GM: { ko: '감비아', en: 'Gambia', code: 'GMB' },
  GE: { ko: '조지아', en: 'Georgia', code: 'GEO' },
  DE: { ko: '독일', en: 'Germany', code: 'DEU' },
  GH: { ko: '가나', en: 'Ghana', code: 'GHA' },
  GI: { ko: '지브롤터', en: 'Gibraltar' },
  GR: { ko: '그리스', en: 'Greece', code: 'GRC' },
  GL: { ko: '그린란드', en: 'Greenland' },
  GD: { ko: '그레나다', en: 'Grenada', code: 'GRD' },
  GP: { ko: '과들루프', en: 'Guadeloupe' },
  GU: { ko: '괌', en: 'Guam' },
  GT: { ko: '과테말라', en: 'Guatemala', code: 'GTM' },
  GG: { ko: '건지 섬', en: 'Guernsey' },
  GN: { ko: '기니', en: 'Guinea', code: 'GIN' },
  GW: { ko: '기니비사우', en: 'Guinea-Bissau', code: 'GNB' },
  GY: { ko: '가이아나', en: 'Guyana', code: 'GUY' },
  HT: { ko: '아이티', en: 'Haiti', code: 'HTI' },
  HM: { ko: '허드 맥도널드 제도', en: 'Heard Island and McDonald Islands' },
  HN: { ko: '온두라스', en: 'Honduras', code: 'HND' },
  HK: { ko: '홍콩', en: 'Hong Kong' },
  HU: { ko: '헝가리', en: 'Hungary', code: 'HUN' },
  IS: { ko: '아이슬란드', en: 'Iceland', code: 'ISL' },
  IN: { ko: '인도', en: 'India', code: 'IND' },
  ID: { ko: '인도네시아', en: 'Indonesia', code: 'IDN' },
  IR: { ko: '이란', en: 'Iran', code: 'IRN' },
  IQ: { ko: '이라크', en: 'Iraq', code: 'IRQ' },
  IE: { ko: '아일랜드', en: 'Ireland', code: 'IRL' },
  IM: { ko: '맨섬', en: 'Isle of Man' },
  IL: { ko: '이스라엘', en: 'Israel', code: 'ISR' },
  IT: { ko: '이탈리아', en: 'Italy', code: 'ITA' },
  CI: { ko: '코트디부아르', en: 'Ivory Coast', code: 'CIV' },
  JM: { ko: '자메이카', en: 'Jamaica', code: 'JAM' },
  JP: { ko: '일본', en: 'Japan', code: 'JPN' },
  JE: { ko: '저지 섬', en: 'Jersey' },
  JO: { ko: '요르단', en: 'Jordan', code: 'JOR' },
  KZ: { ko: '카자흐스탄', en: 'Kazakhstan', code: 'KAZ' },
  KE: { ko: '케냐', en: 'Kenya', code: 'KEN' },
  KI: { ko: '키리바시', en: 'Kiribati', code: 'KIR' },
  XK: { ko: '코소보', en: 'Kosovo', code: 'XKX' },
  KW: { ko: '쿠웨이트', en: 'Kuwait', code: 'KWT' },
  KG: { ko: '키르기스스탄', en: 'Kyrgyzstan', code: 'KGZ' },
  LA: { ko: '라오스', en: 'Laos', code: 'LAO' },
  LV: { ko: '라트비아', en: 'Latvia', code: 'LVA' },
  LB: { ko: '레바논', en: 'Lebanon', code: 'LBN' },
  LS: { ko: '레소토', en: 'Lesotho', code: 'LSO' },
  LR: { ko: '라이베리아', en: 'Liberia', code: 'LBR' },
  LY: { ko: '리비아', en: 'Libya', code: 'LBY' },
  LI: { ko: '리히텐슈타인', en: 'Liechtenstein', code: 'LIE' },
  LT: { ko: '리투아니아', en: 'Lithuania', code: 'LTU' },
  LU: { ko: '룩셈부르크', en: 'Luxembourg', code: 'LUX' },
  MO: { ko: '마카오', en: 'Macau' },
  MK: { ko: '마케도니아', en: 'Macedonia', code: 'MKD' },
  MG: { ko: '마다가스카르', en: 'Madagascar', code: 'MDG' },
  MW: { ko: '말라위', en: 'Malawi', code: 'MWI' },
  MY: { ko: '말레이시아', en: 'Malaysia', code: 'MYS' },
  MV: { ko: '몰디브', en: 'Maldives', code: 'MDV' },
  ML: { ko: '말리', en: 'Mali', code: 'MLI' },
  MT: { ko: '몰타', en: 'Malta', code: 'MLT' },
  MH: { ko: '마셜 제도', en: 'Marshall Islands', code: 'MHL' },
  MQ: { ko: '마르티니크', en: 'Martinique' },
  MR: { ko: '모리타니', en: 'Mauritania', code: 'MRT' },
  MU: { ko: '모리셔스', en: 'Mauritius', code: 'MUS' },
  YT: { ko: '마요트', en: 'Mayotte' },
  MX: { ko: '멕시코', en: 'Mexico', code: 'MEX' },
  FM: { ko: '미크로네시아', en: 'Micronesia', code: 'FSM' },
  MD: { ko: '몰도바', en: 'Moldova', code: 'MDA' },
  MC: { ko: '모나코', en: 'Monaco', code: 'MCO' },
  MN: { ko: '몽골국', en: 'Mongolia', code: 'MNG' },
  ME: { ko: '몬테네그로', en: 'Montenegro', code: 'MNE' },
  MS: { ko: '몬트세랫', en: 'Montserrat' },
  MA: { ko: '모로코', en: 'Morocco', code: 'MAR' },
  MZ: { ko: '모잠비크', en: 'Mozambique', code: 'MOZ' },
  MM: { ko: '미얀마', en: 'Myanmar', code: 'MMR' },
  NA: { ko: '나미비아', en: 'Namibia', code: 'NAM' },
  NR: { ko: '나우루', en: 'Nauru', code: 'NRU' },
  NP: { ko: '네팔', en: 'Nepal', code: 'NPL' },
  NL: { ko: '네덜란드', en: 'Netherlands', code: 'NLD' },
  NC: { ko: '누벨칼레도니', en: 'New Caledonia' },
  NZ: { ko: '뉴질랜드', en: 'New Zealand', code: 'NZL' },
  NI: { ko: '니카라과', en: 'Nicaragua', code: 'NIC' },
  NE: { ko: '니제르', en: 'Niger', code: 'NER' },
  NG: { ko: '나이지리아', en: 'Nigeria', code: 'NGA' },
  NU: { ko: '니우에', en: 'Niue', code: 'NIU' },
  NF: { ko: '노퍽 섬', en: 'Norfolk Island' },
  KP: { ko: '조선', en: 'North Korea' },
  MP: { ko: '북마리아나 제도', en: 'Northern Mariana Islands' },
  NO: { ko: '노르웨이', en: 'Norway', code: 'NOR' },
  OM: { ko: '오만', en: 'Oman', code: 'OMN' },
  PK: { ko: '파키스탄', en: 'Pakistan', code: 'PAK' },
  PW: { ko: '팔라우', en: 'Palau', code: 'PLW' },
  PS: { ko: '팔레스타인', en: 'Palestine', code: 'PSE' },
  PA: { ko: '파나마', en: 'Panama', code: 'PAN' },
  PG: { ko: '파푸아뉴기니', en: 'Papua New Guinea', code: 'PNG' },
  PY: { ko: '파라과이', en: 'Paraguay', code: 'PRY' },
  PE: { ko: '페루', en: 'Peru', code: 'PER' },
  PH: { ko: '필리핀', en: 'Philippines', code: 'PHL' },
  PN: { ko: '핏케언 제도', en: 'Pitcairn Islands' },
  PL: { ko: '폴란드', en: 'Poland', code: 'POL' },
  PT: { ko: '포르투갈', en: 'Portugal', code: 'PRT' },
  PR: { ko: '푸에르토리코', en: 'Puerto Rico' },
  QA: { ko: '카타르', en: 'Qatar', code: 'QAT' },
  CG: { ko: '콩고', en: 'Republic of the Congo', code: 'COG' },
  RO: { ko: '루마니아', en: 'Romania', code: 'ROU' },
  RU: { ko: '러시아', en: 'Russia', code: 'RUS' },
  RW: { ko: '르완다', en: 'Rwanda', code: 'RWA' },
  RE: { ko: '레위니옹', en: 'Réunion' },
  BL: { ko: '생바르텔레미', en: 'Saint Barthélemy' },
  SH: { ko: '세인트헬레나', en: 'Saint Helena, Ascension and Tristan da Cunha' },
  KN: { ko: '세인트키츠 네비스', en: 'Saint Kitts and Nevis', code: 'KNA' },
  LC: { ko: '세인트루시아', en: 'Saint Lucia', code: 'LCA' },
  MF: { ko: '생마르탱', en: 'Saint Martin' },
  PM: { ko: '생피에르 미클롱', en: 'Saint Pierre and Miquelon' },
  VC: {
    ko: '세인트빈센트 그레나딘',
    en: 'Saint Vincent and the Grenadines',
    code: 'VCT',
  },
  WS: { ko: '사모아', en: 'Samoa', code: 'WSM' },
  SM: { ko: '산마리노', en: 'San Marino', code: 'SMR' },
  SA: { ko: '사우디아라비아', en: 'Saudi Arabia', code: 'SAU' },
  SN: { ko: '세네갈', en: 'Senegal', code: 'SEN' },
  RS: { ko: '세르비아', en: 'Serbia', code: 'SRB' },
  SC: { ko: '세이셸', en: 'Seychelles', code: 'SYC' },
  SL: { ko: '시에라리온', en: 'Sierra Leone', code: 'SLE' },
  SG: { ko: '싱가포르', en: 'Singapore', code: 'SGP' },
  SX: { ko: '신트마르턴', en: 'Sint Maarten' },
  SK: { ko: '슬로바키아', en: 'Slovakia', code: 'SVK' },
  SI: { ko: '슬로베니아', en: 'Slovenia', code: 'SVN' },
  SB: { ko: '솔로몬 제도', en: 'Solomon Islands', code: 'SLB' },
  SO: { ko: '소말리아', en: 'Somalia', code: 'SOM' },
  ZA: { ko: '남아프리카', en: 'South Africa', code: 'ZAF' },
  GS: { ko: '조지아', en: 'South Georgia' },
  KR: { ko: '한국', en: 'South Korea', code: 'KOR' },
  SS: { ko: '남수단', en: 'South Sudan', code: 'SSD' },
  ES: { ko: '스페인', en: 'Spain', code: 'ESP' },
  LK: { ko: '스리랑카', en: 'Sri Lanka', code: 'LKA' },
  SD: { ko: '수단', en: 'Sudan', code: 'SDN' },
  SR: { ko: '수리남', en: 'Suriname', code: 'SUR' },
  SJ: { ko: '스발바르 얀마옌 제도', en: 'Svalbard and Jan Mayen' },
  SE: { ko: '스웨덴', en: 'Sweden', code: 'SWE' },
  CH: { ko: '스위스', en: 'Switzerland', code: 'CHE' },
  SY: { ko: '시리아', en: 'Syria', code: 'SYR' },
  ST: { ko: '상투메 프린시페', en: 'São Tomé and Príncipe', code: 'STP' },
  TW: { ko: '대만', en: 'Taiwan' },
  TJ: { ko: '타지키스탄', en: 'Tajikistan', code: 'TJK' },
  TZ: { ko: '탄자니아', en: 'Tanzania', code: 'TZA' },
  TH: { ko: '태국', en: 'Thailand', code: 'THA' },
  TL: { ko: '동티모르', en: 'Timor-Leste', code: 'TLS' },
  TG: { ko: '토고', en: 'Togo', code: 'TGO' },
  TK: { ko: '토켈라우', en: 'Tokelau' },
  TO: { ko: '통가', en: 'Tonga', code: 'TON' },
  TT: { ko: '트리니다드 토바고', en: 'Trinidad and Tobago', code: 'TTO' },
  TN: { ko: '튀니지', en: 'Tunisia', code: 'TUN' },
  TR: { ko: '터키', en: 'Turkey', code: 'TUR' },
  TM: { ko: '투르크메니스탄', en: 'Turkmenistan', code: 'TKM' },
  TC: { ko: '터크스 케이커스 제도', en: 'Turks and Caicos Islands' },
  TV: { ko: '투발루', en: 'Tuvalu', code: 'TUV' },
  UG: { ko: '우간다', en: 'Uganda', code: 'UGA' },
  UA: { ko: '우크라이나', en: 'Ukraine', code: 'UKR' },
  AE: { ko: '아랍에미리트', en: 'United Arab Emirates', code: 'ARE' },
  GB: { ko: '영국', en: 'United Kingdom', code: 'GBR' },
  US: { ko: '미국', en: 'United States', code: 'USA' },
  UM: { ko: '미국령 군소 제도', en: 'United States Minor Outlying Islands' },
  VI: { ko: '미국령 버진아일랜드', en: 'United States Virgin Islands' },
  UY: { ko: '우루과이', en: 'Uruguay', code: 'URY' },
  UZ: { ko: '우즈베키스탄', en: 'Uzbekistan', code: 'UZB' },
  VU: { ko: '바누아투', en: 'Vanuatu', code: 'VUT' },
  VA: { ko: '바티칸', en: 'Vatican City', code: 'VAT' },
  VE: { ko: '베네수엘라', en: 'Venezuela', code: 'VEN' },
  VN: { ko: '베트남', en: 'Vietnam', code: 'VNM' },
  WF: { ko: '왈리스 푸투나', en: 'Wallis and Futuna' },
  EH: { ko: '서사하라', en: 'Western Sahara' },
  YE: { ko: '예멘', en: 'Yemen', code: 'YEM' },
  ZM: { ko: '잠비아', en: 'Zambia', code: 'ZMB' },
  ZW: { ko: '짐바브웨', en: 'Zimbabwe', code: 'ZWE' },
  AX: { ko: '올란드 제도', en: 'Åland Islands' },
};
